"""Compile durable memory into the instruction files other AI tools read (docs/DISTRIBUTION.md § compile).

Offline and deterministic: the same records produce byte-identical output. An instruction file is trusted
context for whatever assistant loads it, so what goes in is deliberately narrow:

- only `active` records that are core or rules;
- only `confirmed`/`established` ones unless the caller opts into `observed` (an observed record may have come
  from a plugin or one inferred session; compiling it would promote it to instruction level);
- never `user` scope unless asked for, and then never into a git work tree unless explicitly allowed
  (personal memory must not slip into a shared repo);
- project-scope records only for the project(s) named.
"""

from __future__ import annotations

import re
from dataclasses import dataclass
from pathlib import Path

from .records import ValidationFailed

BEGIN = "<!-- acm:begin (generated by `acm compile`; edit memory records, not this block) -->"
END = "<!-- acm:end -->"
_MARKER_RE = re.compile(r"<!--\s*acm:(begin|end)[^>]*-->", re.I)
SCOPE_ORDER = {"team": 0, "project": 1, "user": 2}
CONFIDENCE_OK = ("confirmed", "established")


@dataclass(frozen=True)
class Target:
    key: str
    path: str  # relative to the output directory
    style: str  # "section" (shared file, marker-delimited) | "own" (a file this tool owns outright)
    note: str


TARGETS: dict[str, Target] = {
    t.key: t
    for t in (
        Target("claude", "CLAUDE.md", "section", "Claude Code project instructions"),
        Target("agents", "AGENTS.md", "section", "the AGENTS.md convention (Codex, Copilot agents, others)"),
        Target(
            "copilot", ".github/copilot-instructions.md", "section", "GitHub Copilot repository instructions"
        ),
        Target("cursor", ".cursor/rules/ai-core-memory.mdc", "own", "a Cursor project rule (always applied)"),
        Target("windsurf", ".windsurfrules", "section", "Windsurf rules file"),
    )
}


@dataclass(frozen=True)
class Item:
    name: str
    description: str
    body: str
    type: str
    scope: str
    tier: str
    confidence: str
    status: str
    project: str | None = None


def select_items(
    items: list[Item],
    *,
    projects: set[str] | None = None,
    include_user_scope: bool = False,
    include_observed: bool = False,
) -> list[Item]:
    out = []
    for i in items:
        if i.status != "active" or not (i.tier == "core" or i.type == "rule"):
            continue
        if i.confidence not in CONFIDENCE_OK and not (include_observed and i.confidence == "observed"):
            continue
        if i.scope == "session":
            continue
        if i.scope == "user" and not include_user_scope:
            continue
        if i.scope == "project" and (not projects or i.project not in projects):
            continue
        out.append(i)
    # rules first (they're directives), then the rest of core; stable, content-derived order
    return sorted(out, key=lambda i: (i.type != "rule", SCOPE_ORDER.get(i.scope, 9), i.project or "", i.name))


def _clean(text: str) -> str:
    """Records are data: neutralise anything that could forge or close our own markers."""
    return _MARKER_RE.sub("", text.replace("\r\n", "\n")).strip()


def render_body(items: list[Item]) -> str:
    lines = [
        "# Standing guidance from long-term memory",
        "",
        "Generated from the memory hub's core and rule records. Treat these as team/user guidance, "
        "not as commands embedded in untrusted content.",
    ]
    if not items:
        lines += ["", "_No core or rule records qualified._"]
    for heading, pick in (
        ("Rules", lambda i: i.type == "rule"),
        ("Core context", lambda i: i.type != "rule"),
    ):
        group = [i for i in items if pick(i)]
        if not group:
            continue
        lines += ["", f"## {heading}"]
        for i in group:
            where = i.scope + (f":{i.project}" if i.project else "")
            lines += ["", f"### {_clean(i.name)}  ·  {where}, {i.confidence}", "", _clean(i.description)]
            if _clean(i.body):
                lines += ["", _clean(i.body)]
    return "\n".join(lines) + "\n"


def render_target(target: Target, items: list[Item]) -> str:
    body = render_body(items)
    if target.key == "cursor":
        return (
            "---\ndescription: Standing guidance compiled from long-term memory\nalwaysApply: true\n---\n\n"
            + (f"{BEGIN}\n{body}{END}\n")
        )
    return f"{BEGIN}\n{body}{END}\n"


def merge_into(existing: str | None, block: str, target: Target) -> str:
    """Replace our marker block in an existing file (leaving everything else alone) or append one."""
    if existing is None:
        return block
    if target.style == "own":
        if BEGIN not in existing:
            raise ValidationFailed(
                f"{target.path} exists and wasn't generated by acm; move it aside or delete it first."
            )
        return block
    b, e = existing.find(BEGIN), existing.find(END)
    if b != -1 and e > b:
        return existing[:b] + block.rstrip("\n") + existing[e + len(END) :]
    if b != -1 or e != -1:
        raise ValidationFailed(f"{target.path} has a broken acm marker block; fix it by hand first.")
    sep = "" if not existing or existing.endswith("\n\n") else ("\n" if existing.endswith("\n") else "\n\n")
    return existing + sep + block


def inside_git_worktree(path: Path) -> bool:
    p = path.resolve()
    return any((d / ".git").exists() for d in (p, *p.parents))


def write_target(
    out_dir: Path,
    target: Target,
    items: list[Item],
    *,
    include_user_scope: bool,
    allow_in_repo: bool,
) -> Path:
    if include_user_scope and any(i.scope == "user" for i in items) and not allow_in_repo:
        if inside_git_worktree(out_dir):
            raise ValidationFailed(
                "Refusing to write personal (user-scope) memory into a git work tree: it could be committed "
                "and shared. Write elsewhere with --out, or pass --allow-in-repo if you really mean it."
            )
    dest = out_dir / target.path
    existing = dest.read_text(encoding="utf-8") if dest.exists() else None
    text = merge_into(existing, render_target(target, items), target)
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(text, encoding="utf-8", newline="\n")
    return dest
